FROM mysql:8.0.28-oracle

USER 0

COPY ./conf/replica /etc/mysql/conf.d
COPY ./init/mysql/replica /init-mysql
COPY ./init/db /init-db
COPY ./init/init.sh /docker-entrypoint-initdb.d/01-init.sh
#COPY ./init/seeding.sh /docker-entrypoint-initdb.d/02-seeding.sh

ENV TZ=Asia/Seoul
ENV MYSQL_ROOT_PASSWORD=1234
